### ISSUE TITLE
INSTALL.html could cover some things in more detail

### ISSUE THREAD

**Issue by kentfredric** [perlorg/cpanorg#27]
Listing the recommended modules such as local::lib and soforth are a good start.

But it appears necessary to have documented somewhere an overview of how one should use those modules ( ie: instead of requiring users to read all the documentation of all the modules, a simplified starter on how to use them would be useful ).

As would a more detailed advice section on the advantages of separation of yourself from the system perl, in an attempt to discourage people's *first* option being "sudo" ( Which can entirely break their linux and their vendors install toolchain )

Unfortunately, although I'd like to see such changes, I'm not entirely sure of the best way to write them, and my prose skills are very limited, so this bug will serve as more of a discussion of what /could/ be done and the overall flow prior to somebody attempting it:

Because arguably, some of these elements are politicalised in nature, and we'd need to iron out common requirements first.

**Comment by ranguard** [comment]
@kentfredric unless someone provides a pull request this isn't likely to get done. Please work with #toolchain or whom ever you think relevant to help you produce a pull request. I'm happy to help with final copy cleanup so don't worry about perfection
