### ISSUE TITLE
gmake.exe and perl.exe constantly updated

### ISSUE THREAD

**Issue by PhilterPaper** [perlorg/cpanorg#54]
I'm not sure whether this is a CPAN issue or Strawberry Perl issue, and if the former, if there's a better repository to report this under. 

Anyway, of late (last 2 or 3 months), every time I run `cpan` on Strawberry Perl to upgrade my library of installed packages, my AntiVirus tells me that gmake.exe has been updated -- do I want to proceed? Frequently, I also get a warning that perl.exe has been updated. Is this expected behavior? I'm guessing that it may not be the Strawberry package, as it's every time I run `cpan` to update. Are you packaging fresh copies of gmake and maybe Perl every day?

This is a problem for me because the warning about the update suspends the update process until I give permission to proceed. I can't just fire off the massive daily update (for three Perl versions) and forget about it. It would be nice to have these utilities only update when they've been changed.

**Comment by rspier** [comment]
This repository is for the cpan.org website itself, not for CPAN or Perl.

Your issue sounds to me like it would be best triaged by Strawberry Perl.  See https://strawberryperl.com/support.html for next steps.
