### ISSUE TITLE
5.26.3 missing

### ISSUE THREAD

**Issue by eserte** [perlorg/cpanorg#55]
https://www.cpan.org/src/README.html lists 5.26.2 as the latest release for major 5.26, but according to https://github.com/Perl/perl5/blob/50fa0906cafc0e8c5309e293c2c2ded4d50a9e25/pod/perlhist.pod#the-records there's also a 5.26.3. I guess that the data comes from http://search.cpan.org/api/dist/perl (surprising, search.cpan.org is still active?) where only 5.26.3-RC1 is listed, but no 5.26.3.

**Comment by rspier** [comment]
There is definitely a 5.26.3.

`CPAN/authors/id/S/SH/SHAY/perl-5.26.3.tar.xz`

That legacy API is served by metacpan.  Please reach out to them about it.
