### ISSUE TITLE
/modules/by-X not useful - so do not link to - same for scripts/?

### ISSUE THREAD

**Issue by ranguard** [perlorg/cpanorg#66]
After looking at cpan.metacpan.org logs for `/modules/by-...` it seems they are just full of bots and not much else (though I can't be 100%!). 

These directories are full of symlinks which actually means bots are downloading multiple copies of the same files. 

Also as these are all symlinks, our BackPAN ends up with something like 50 Million files, instead of under 2 Million when these directories are excluded. (I'm looking at uploading MetaCPAN's BackPAN to an object store which doesn't support symlinks, I was just going to make copies of files until I found the scale of this).

I asked on #pts and Ricardo Signes  said "I don't think they're used."

I'll submit a PR to remove the HTML links to these directories - if I've missed a reason we should keep linking to them I'm sure you'll let me know :)

**Comment by rspier** [comment]
> These directories are full of symlinks which actually means bots are downloading multiple copies of the same files.

Poor bots.  A better solution in this case would be to serve these as redirects.  The bots will probably still down load them multiple times.  (But the bots probably need to be throttled anyway.)

> If you're trying to solve for backpan, you should just exclude the modules directory.  The master Backpan just updates `authors/id`.  It still has some older content in the modules directory from a loooooooong time ago.

@abh @andk   What do you think?  I'm not opposed to getting rid of the modules links on the web version, but it just covers over the real issue.  They're still "updated".  It is likely they're highly unused -- but in that case we should just stop generating them and delete them.

**Comment by ranguard** [comment]
> > These directories are full of symlinks which actually means bots are downloading multiple copies of the same files.
> 
> Poor bots. A better solution in this case would be to serve these as redirects. The bots will probably still down load them multiple times. (But the bots probably need to be throttled anyway.)

I did have a quick look at redirects, but you'd need a very large lookup list to do it and for BackPAN I'm trying to get it to a point we arn't even running nginx (Object Store + Fastly) and whilst I could do some computer@edge thing it all seemed like more effort than it was worth :)

We've started adding throttling to various services - which was one of the reasons we started looking at these logs.

> > If you're trying to solve for backpan, you should just exclude the modules directory.  The master Backpan just updates `authors/id`.  It still has some older content in the modules directory from a loooooooong time ago.

Yea, we will for MC BackPAN - I'm now serving 404's for /modules/by-* - and now about 60% of our replies are 404! - I'm sure the bots will learn.. eventually :)

**Comment by ranguard** [comment]
If we are cleaning up.. should we also remove https://www.cpan.org/scripts/  ?

https://www.cpan.org/scripts/submitting.html talks about emails the scripts mailing list - which I can't see on https://lists.perl.org/all.html#s

**Comment by abh** [comment]
> [ removing /scripts/ ]

That makes sense to me. The actual scrips will still be there, just not the ~20 years out of date index of them.

**Comment by ranguard** [comment]
Updated https://github.com/perlorg/cpanorg/pull/67 to also remove reference to scripts/ (can always be cherry picked if one part of this is accepted but not the other)

**Comment by rspier** [comment]
Less is more.   Let's do it.

**Comment by ranguard** [comment]
Just to make findable...

https://www.reddit.com/r/perl/comments/1hdktb4/this_late_evening_work_is_sponsored_by_metacpan/ raised that some Fedora packagers do use modules-by/ - I've asked Perl Toolchain Summit to discuss

**Comment by abh** [comment]
@ranguard can those be updated reasonably easily or are some of them "baked forever"?

For www.cpan.org we could relatively easily "bake in" all the existing links (and make the file URLs 301 redirects) but stop updating new ones.

If they need to work forever PAUSE could generate a map (just a TSV file?) and web servers could use that to build redirects as appropriate.

**Comment by ranguard** [comment]
> [@ranguard](https://github.com/ranguard) can those be updated reasonably easily or are some of them "baked forever"?

I don't really know... but I guess long term it ideal as could be referenced from old packaged archives

> For [www.cpan.org](http://www.cpan.org) we could relatively easily "bake in" all the existing links (and make the file URLs 301 redirects) but stop updating new ones.
> 
> If they need to work forever PAUSE could generate a map (just a TSV file?) and web servers could use that to build redirects as appropriate.

Sounds sensible - I wasn't at PTS this year but will try raise it somewhere/sometime!

In the mean time @abh are you ok if I redirect cpan.metacpan.org/modules/by-* to www.cpan.org/... ?

**Comment by ranguard** [comment]
Hi @abh / @rspier,

I've just put these redirects in live. 

We've finally got control of metacpan.org traffic - only after using Fastly Dynamic challenges to stop the bots - thought https://github.com/metacpan/metacpan-k8s/issues/154 might be interesting and we now have a public dashboard at https://p.datadoghq.eu/sb/c2941b7b-37bb-11f0-94e3-32bf19abf102-744ae84f98611bfd6781365a482e2155 (still a bit of a work in progress).

All the best

Leo
